models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo-instruct

  - type: llama_guard
    engine: vllm_openai
    parameters:
      openai_api_base: "http://localhost:5000/v1"
      model_name: "meta-llama/LlamaGuard-7b"

rails:
  input:
    flows:
      - llama guard check input

  output:
    flows:
      - llama guard check output
